inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Exclude:
    - 'test/**/*'

Naming/PredicateMethod:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false
