inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety

ThreadSafety:
  Enabled: true
  Exclude:
    - "**/*.gemspec"
    - test/**/*

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/benchmark_*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Exclude:
    - 'test/**/*'

Naming/PredicateMethod:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false
