inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Exclude:
    - 'test/**/*'
