fix: false               # default: false
parallel: true          # default: false
ruby_version: 3.1       # default: RUBY_VERSION
default_ignores: false  # default: true

ignore:                 # default: []
  - 'test/**/*':
    - Style/GlobalVars
    - Style/Semicolon
