name: RuboCop

on: [push, pull_request]

concurrency:
  group: rubocop-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Ruby
      uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
      with:
        ruby-version: ruby
        bundler-cache: true # 'bundle install' and cache
    - name: Run RuboCop
      run: bundle exec rubocop --parallel --color
